In [6]:
import random
I = 5000


In [7]:
import numpy as np

In [8]:
rng = np.random.default_rng()

In [9]:
%time mat = rng.standard_normal((I, I))

CPU times: user 218 ms, sys: 84.7 ms, total: 303 ms
Wall time: 301 ms


In [10]:
mat.nbytes

200000000

In [11]:
import sys

In [12]:
sys.getsizeof(mat)

200000128

In [13]:
dt = np.dtype([('Name', 'S10'), ('Age', 'i4'), ('Height', 'f'), ('Children/Pets', 'i4', 2)])

In [14]:
dt

dtype([('Name', 'S10'), ('Age', '<i4'), ('Height', '<f4'), ('Children/Pets', '<i4', (2,))])

In [15]:
dt = np.dtype({'names': ['Name', 'Age', 'Height', 'Children/Pets'],
              'formats': 'O int float int,int'.split()})


In [16]:
dt

dtype([('Name', 'O'), ('Age', '<i8'), ('Height', '<f8'), ('Children/Pets', [('f0', '<i8'), ('f1', '<i8')])])

In [17]:
s = np.array([('Smith', 45, 1.83, (0, 1)),
             ('Jones', 53, 1.72, (2, 2))], dtype=dt)


In [18]:
s

array([('Smith', 45, 1.83, (0, 1)), ('Jones', 53, 1.72, (2, 2))],
      dtype=[('Name', 'O'), ('Age', '<i8'), ('Height', '<f8'), ('Children/Pets', [('f0', '<i8'), ('f1', '<i8')])])

In [19]:
type(s)

numpy.ndarray

In [20]:
s['Name']

array(['Smith', 'Jones'], dtype=object)

In [21]:
s['Height']

array([1.83, 1.72])

In [22]:
s['Height'].mean()

1.775

In [23]:
s[0]

('Smith', 45, 1.83, (0, 1))

In [24]:
s[1]['Age']

53

In [25]:
np.random.seed(100)
r = np.arange(12).reshape((4, 3))
s = np.arange(12).reshape((4, 3)) * 0.5


In [26]:
r

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [27]:
s

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ],
       [4.5, 5. , 5.5]])

In [28]:
r + s

array([[ 0. ,  1.5,  3. ],
       [ 4.5,  6. ,  7.5],
       [ 9. , 10.5, 12. ],
       [13.5, 15. , 16.5]])

In [29]:
r + 3

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [30]:
r


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [31]:
r.shape

(4, 3)

In [32]:
s = np.arange(0, 12, 4)

In [33]:
s

array([0, 4, 8])

In [34]:
r + s

array([[ 0,  5, 10],
       [ 3,  8, 13],
       [ 6, 11, 16],
       [ 9, 14, 19]])

In [35]:
s = np.arange(0, 12, 3)

In [36]:
s

array([0, 3, 6, 9])

In [38]:
r.transpose() + s

array([[ 0,  6, 12, 18],
       [ 1,  7, 13, 19],
       [ 2,  8, 14, 20]])

In [39]:
sr = s.reshape(-1, 1)

In [40]:
sr

array([[0],
       [3],
       [6],
       [9]])

In [41]:
sr.shape

(4, 1)

In [43]:
def f(x):
    return 3 * x + 5


In [44]:
f(0.5)

6.5

In [45]:
f(r)

array([[ 5,  8, 11],
       [14, 17, 20],
       [23, 26, 29],
       [32, 35, 38]])

In [53]:
x = rng.standard_normal((1000000, 5))
x

array([[-1.59668451, -1.74321898, -0.44082243, -0.46603659,  0.9375552 ],
       [ 0.09312732, -0.54257358, -1.20019256,  0.23622522,  1.22176199],
       [-0.41998839, -0.75677209, -0.95367788,  0.58361184,  1.48888239],
       ...,
       [ 0.04948906, -0.55692224,  0.12952723,  0.4544553 , -1.28590724],
       [-2.36701414, -0.89563745,  0.86896276, -0.77297465, -2.05931031],
       [-2.10725051,  0.09678989, -0.28254499,  0.56030491, -0.08689588]])

In [54]:
y = 2 * x + 3
y


array([[-0.19336901, -0.48643797,  2.11835513,  2.06792682,  4.87511041],
       [ 3.18625464,  1.91485283,  0.59961488,  3.47245045,  5.44352397],
       [ 2.16002322,  1.48645581,  1.09264423,  4.16722368,  5.97776478],
       ...,
       [ 3.09897813,  1.88615553,  3.25905447,  3.90891061,  0.42818553],
       [-1.73402829,  1.2087251 ,  4.73792552,  1.4540507 , -1.11862062],
       [-1.21450101,  3.19357978,  2.43491003,  4.12060981,  2.82620823]])

In [56]:
C = np.array((x, y), order='C')
C.shape

(2, 1000000, 5)

In [57]:
F = np.array((x, y), order='F')
F.shape

(2, 1000000, 5)

In [61]:
sys.getsizeof(x)

40000128

In [63]:
x = 0.0; y = 0.0

In [64]:
sys.getsizeof(x)

24

In [66]:
C[0].round(2)

array([[-1.6 , -1.74, -0.44, -0.47,  0.94],
       [ 0.09, -0.54, -1.2 ,  0.24,  1.22],
       [-0.42, -0.76, -0.95,  0.58,  1.49],
       ...,
       [ 0.05, -0.56,  0.13,  0.45, -1.29],
       [-2.37, -0.9 ,  0.87, -0.77, -2.06],
       [-2.11,  0.1 , -0.28,  0.56, -0.09]])

In [67]:
C.shape

(2, 1000000, 5)

In [68]:
%timeit C.sum()

1.83 ms ± 12.8 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [69]:
%timeit F.sum()

1.83 ms ± 10 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
